
# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  deploy app
# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Shared configuration for all resources, more in
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  Env:
    Type: String
    AllowedValues:
      - production
      - development
    Default: development

Mappings:
  EnvMap:
    development:
      Function: 'developmentFunction'
      Handler: 'src/handlers/development.handler'
      Description: 'connected to development branch'
      Api: 'developmentApi'
      StageName: 'development'
    production:
      Function: 'productionFunction'
      Handler: 'src/handlers/production.handler'
      Description: 'connected to production branch'
      Api: 'productionApi'
      StageName: 'production'

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: index.js
  developmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: !FindInMap [ EnvMap, !Ref Env, Handler ]
      Runtime: nodejs10.x
      Role: arn:aws:iam::968525956953:role/githubActions
      MemorySize: 128
      Timeout: 60
      Description: !FindInMap [ EnvMap, !Ref Env, Description ]
      Policies:
        - AmazonAPIGatewayInvokeFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref developmentApi
  #           RestApiId: !FindInMap [ EnvMap, !Ref Env, Api ]

  # !FindInMap [ EnvMap, !Ref Env, Api ]:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #    StageName: !FindInMap [ EnvMap, !Ref Env, StageNamei ]
     
    developmentApi:
    Type: AWS::Serverless::Api
    Properties:
     StageName: !FindInMap [ EnvMap, !Ref Env, StageName ]
