# This is a basic workflow to help you get started with Actions

name: AWS SAM deploy production app 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      #install python and aws-sam-cli
      - name: Set up python
        uses: actions/setup-python@v2
        with:
           python-version: 3.6
      - run: |
         python -m pip install --upgrade pip
         pip install awscli
         pip install aws-sam-cli
   
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: deploy production app
        run: bash production.sh
        shell: bash

      - name: Slack Notify on success
        if: success()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GithubActions
          SLACK_MESSAGE: successfully deployed 
          SLACK_TITLE: Message
          SLACK_COLOR: '#008000'

      - name: Slack Notify on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GithubActions
          SLACK_MESSAGE: deployment failed 
          SLACK_TITLE: Message
          SLACK_COLOR: '#FF0000'


          
